// <auto-generated />
using CachingPoc.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CachingPoc.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260720155531_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("CachingPoc.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Keyboard",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mouse",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Monitor",
                            Price = 149.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
